# Generated by Django 2.1.4 on 2019-01-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(default='Blog', max_length=255),
        ),
    ]
